"""
Brain Event Models

Typed event dataclasses for the event bus. Each event has a unique ID,
timestamp, source module, and typed payload.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _new_id() -> str:
    return str(uuid.uuid4())


class EventType(str, Enum):
    TICK = "tick"
    FEATURE_COMPUTED = "feature.computed"
    REGIME_CHANGED = "regime.changed"
    SIGNAL_GENERATED = "signal.generated"
    ALERT_TRIGGERED = "alert.triggered"
    MODEL_PREDICTION = "model.prediction"
    SENTIMENT_UPDATE = "sentiment.update"
    RISK_BREACH = "risk.breach"
    AGENT_ANALYSIS = "agent.analysis"


@dataclass
class BrainEvent:
    """Base event for the Brain event bus."""
    event_type: EventType = EventType.TICK
    event_id: str = field(default_factory=_new_id)
    timestamp: datetime = field(default_factory=_utcnow)
    source: str = ""
    payload: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TickEvent(BrainEvent):
    """Market tick data event."""
    symbol: str = ""
    price: float = 0.0
    volume: int = 0
    bid: float = 0.0
    ask: float = 0.0

    def __post_init__(self):
        self.event_type = EventType.TICK
        self.source = self.source or "market_data"


@dataclass
class FeatureEvent(BrainEvent):
    """Feature computation completed for a symbol."""
    symbol: str = ""
    feature_count: int = 0
    features: Dict[str, float] = field(default_factory=dict)

    def __post_init__(self):
        self.event_type = EventType.FEATURE_COMPUTED
        self.source = self.source or "feature_engine"


class MarketRegime(str, Enum):
    BULL = "bull"
    BEAR = "bear"
    SIDEWAYS = "sideways"


@dataclass
class RegimeEvent(BrainEvent):
    """Market regime change detected."""
    regime: MarketRegime = MarketRegime.SIDEWAYS
    bull_probability: float = 0.33
    bear_probability: float = 0.33
    sideways_probability: float = 0.34
    previous_regime: Optional[MarketRegime] = None

    def __post_init__(self):
        self.event_type = EventType.REGIME_CHANGED
        self.source = self.source or "regime_detector"


class SignalDirection(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class SignalTimeframe(str, Enum):
    INTRADAY = "intraday"
    SWING = "swing"           # 1-5 days
    POSITIONAL = "positional"  # 1-4 weeks
    INVESTMENT = "investment"  # 1-12 months


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


@dataclass
class ContributingFactor:
    """A factor contributing to a signal."""
    name: str
    score: float        # [-1, +1]
    weight: float       # [0, 1]
    description: str = ""


@dataclass
class SignalEvent(BrainEvent):
    """Trading signal generated by the Brain."""
    signal_id: str = field(default_factory=_new_id)
    symbol: str = ""
    company: str = ""
    sector: str = ""
    direction: SignalDirection = SignalDirection.HOLD
    confidence: float = 0.0           # 0-100%
    timeframe: SignalTimeframe = SignalTimeframe.SWING
    entry_price: float = 0.0
    target_price: float = 0.0
    stop_loss: float = 0.0
    risk_reward_ratio: float = 0.0
    risk_level: RiskLevel = RiskLevel.MEDIUM
    contributing_factors: List[ContributingFactor] = field(default_factory=list)
    explanation: str = ""
    shap_features: Dict[str, float] = field(default_factory=dict)
    regime_at_signal: Optional[MarketRegime] = None
    model_version: str = ""

    def __post_init__(self):
        self.event_type = EventType.SIGNAL_GENERATED
        self.source = self.source or "signal_fusion"


@dataclass
class AlertEvent(BrainEvent):
    """Alert triggered by the Brain."""
    alert_id: str = ""
    symbol: str = ""
    alert_type: str = ""       # price, technical, sentiment, risk
    priority: str = "P2"       # P1 (critical), P2 (important), P3 (informational)
    message: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        self.event_type = EventType.ALERT_TRIGGERED
        self.source = self.source or "alert_engine"


@dataclass
class ModelPredictionEvent(BrainEvent):
    """ML model prediction output."""
    symbol: str = ""
    model_name: str = ""
    model_version: str = ""
    direction: SignalDirection = SignalDirection.HOLD
    probability: float = 0.5
    predicted_return: float = 0.0
    horizon_days: int = 5
    shap_top_features: Dict[str, float] = field(default_factory=dict)

    def __post_init__(self):
        self.event_type = EventType.MODEL_PREDICTION
        self.source = self.source or "model_serving"


@dataclass
class SentimentEvent(BrainEvent):
    """Sentiment update for a symbol or market."""
    symbol: str = ""           # Empty string = market-wide
    sentiment_score: float = 0.0  # [-1, +1]
    positive_prob: float = 0.0
    negative_prob: float = 0.0
    neutral_prob: float = 0.0
    article_count: int = 0
    source_breakdown: Dict[str, float] = field(default_factory=dict)

    def __post_init__(self):
        self.event_type = EventType.SENTIMENT_UPDATE
        self.source = self.source or "sentiment_pipeline"


@dataclass
class RiskBreachEvent(BrainEvent):
    """Risk limit breach detected."""
    breach_type: str = ""      # drawdown, var, position_limit, sector_concentration
    severity: str = "WARNING"  # WARNING, CRITICAL, EMERGENCY
    current_value: float = 0.0
    threshold: float = 0.0
    action_taken: str = ""     # halve_positions, halt_entries, kill_switch
    affected_symbols: List[str] = field(default_factory=list)

    def __post_init__(self):
        self.event_type = EventType.RISK_BREACH
        self.source = self.source or "risk_engine"
